### PR TITLE
Compose v2 and some other changes

### PR DESCRIPTION
**Pull request by kleintom**
This started out as changing to `docker compose` instead of `docker-compose`, but I wound up adding some other stuff, let me know if I can split it up in any way.

I expanded on the debugging material under `Develop!`, but it could maybe still use some more (maybe as its own document?), like using the rails console, I'm sure some other tricks.

### CODE REVIEW

**Comment by LocoDelAssembly** [comment]
On Ubuntu 22.04 LTS `docker compose` is not available apparently (I'm a bit surprised about this, I'd swear I used this new method before, but apparently not on this computer).
```
$ dpkg -l | grep docker.io
ii  docker.io                                      24.0.5-0ubuntu1~22.04.1                 amd64        Linux container runtime
ii  python3-docker                                 5.0.3-1                                 all          Python 3 wrapper to access docker.io's control socket
$ docker compose build      
docker: 'compose' is not a docker command.
See 'docker --help'
$ docker -v                 
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
```

Was there any significant improvement on using compose subcommand instead of `docker-compose` @kleintom?

**Comment by kleintom** [comment]
> Was there any significant improvement on using compose subcommand instead of `docker-compose`?

No, just seeing you had updated the usage in https://github.com/SpeciesFileGroup/taxonworks/commit/fb167ce7a487d6b07f00192e4b18bfd94cfec668 (which I guess must run in a more modern environment) and the docker warning at their migration page: `The final Compose V1 release, version 1.29.2, was May 10, 2021. These packages haven't received any security updates since then. Use at your own risk.`  And wanting new users to start on `docker compose` instead of having to switch later, but that's not a big deal.

Should I revert that change for now?

**Comment by LocoDelAssembly** [comment]
Oh I see, that is because GitHub CI changed docker version and docker-compose is no longer available. Also, on my home computer (which uses an even older Ubuntu), I probably installed docker directly from docker sources rather than using Ubuntu-provided package.

Either, revert that, or add note that if it doesn't work then use `docker-compose`.

**Comment by kleintom** [comment]
> Either, revert that, or add note that if it doesn't work then use `docker-compose`.

I added a note, see what you think - thanks!

**Comment by LocoDelAssembly** [comment]
Perfect thanks! Do I merge now?

**Comment by kleintom** [comment]
Sounds good to me :-)

**Pull request merged**
